# -*- coding: utf-8 -*-
import os
from PIL import Image, ImageDraw, ImageFont

# 定义目录结构
DIRS = [
    "source/documents",
    "source/downloads",
    "source/markor",
    "source/pictures"
]

def ensure_dirs():
    for d in DIRS:
        os.makedirs(d, exist_ok=True)

def create_text_file(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[Text] Created: {path}")

def create_dummy_pdf(path):
    # 创建一个极简的 PDF 文件头，确保文件管理器识别为 PDF
    pdf_content = (
        b"%PDF-1.4\n"
        b"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
        b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
        b"3 0 obj<</Type/Page/MediaBox[0 0 595 842]/Parent 2 0 R/Resources<<>>>>endobj\n"
        b"xref\n0 4\n0000000000 65535 f\n0000000010 00000 n\n0000000060 00000 n\n0000000117 00000 n\n"
        b"trailer<</Size 4/Root 1 0 R>>\nstartxref\n223\n%%EOF\n"
    )
    with open(path, "wb") as f:
        f.write(pdf_content)
    print(f"[PDF]  Created: {path}")

def create_image(path, text=None, color=(200, 200, 200)):
    # 创建一个 800x600 的图片
    img = Image.new('RGB', (800, 600), color=color)
    
    if text:
        draw = ImageDraw.Draw(img)
        # 尝试使用默认字体，如果为了更美观可以加载 ttf
        try:
            # 简单的居中绘制文字
            # 注意：默认字体可能很小，为了演示效果我们尽量画大一点或多画几次
            # 这里简单处理，画在左上角
            draw.text((50, 250), text, fill=(0, 0, 0))
            # 如果需要更清晰的文字用于 OCR 测试，建议画大一点
            draw.text((50, 300), "OCR TEST TARGET", fill=(0, 0, 0))
        except Exception as e:
            print(f"Warning drawing text: {e}")
            
    img.save(path)
    print(f"[IMG]  Created: {path}")

def main():
    ensure_dirs()

    # ==========================
    # 1. Documents
    # ==========================
    # 题目: ...find the name of the PDF file regarding budget... Answer: budget_2025.pdf
    create_dummy_pdf("source/documents/budget_2025.pdf")

    # 题目: ...tell me the passcode written inside. Answer: 8844
    create_text_file("source/documents/secret.txt", 
        "CONFIDENTIAL PROJECT\n\nPasscode: 8844\n\nDo not share.")

    # 题目: ...tell me the word next to that code (1234). Answer: Blueberry
    # 注意：这里的 1234 对应短信里 Alice 发来的验证码
    create_text_file("source/documents/encrypted_note.txt", 
        "Code List V2:\n\n1111: Apple\n1234: Blueberry\n9999: Cherry")

    # ==========================
    # 2. Downloads
    # ==========================
    # 题目: ...file size of 'installer.zip'? Answer: 5MB
    # 注意：你的 inject_files.py 脚本里已经有自动生成 installer.zip 的逻辑了
    # 这里我们生成一个小的占位符即可，注入脚本会覆盖它，或者你可以这里直接生成
    # 为了保持一致性，如果你不想依赖注入脚本的自动生成，可以解开下面注释：
    # with open("source/downloads/installer.zip", "wb") as f: f.write(os.urandom(5 * 1024 * 1024))
    print("[ZIP]  Skipped installer.zip (Will be generated by inject_files.py)")

    # ==========================
    # 3. Markor
    # ==========================
    # 题目: ...What is the third item in the list? Answer: Milk
    create_text_file("source/markor/shopping_list.md", 
        "# Shopping List\n- [ ] Eggs\n- [ ] Bread\n- [ ] Milk\n- [ ] Butter")

    # 题目: ...Who is listed as the 'Minute Taker'? Answer: David
    create_text_file("source/markor/meeting_minutes.txt", 
        "Meeting Date: 2025-10-10\nMinute Taker: David\n\nTopics:\n1. Q4 Goals")

    # 题目: ...read the allocated amount for 'Transport'... Answer: 100
    create_text_file("source/markor/Budget.md", 
        "# Monthly Budget\n\n- Rent: 1000\n- Transport: 100\n- Food: 200")

    # ==========================
    # 4. Pictures
    # ==========================
    # 题目: ...find the image named 'passport_photo.jpg'. What is the date it was taken?
    # 重点是文件名和元数据(时间)，图片内容随意
    create_image("source/pictures/passport_photo.jpg", text="Passport Photo", color=(100, 150, 255))

    # 题目: ...'invoice_001.jpg'... What is the total amount visible...? Answer: 500
    # 这是一个潜在的 OCR 题，我们把 500 写在图片上
    create_image("source/pictures/invoice_001.jpg", text="INVOICE #001\n\nTotal Amount: 500\nStatus: Paid", color=(255, 255, 200))

    print("\n✅ 所有源文件已准备就绪！现在可以运行 main.py 了。")

if __name__ == "__main__":
    main()